/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calc.cliente.view;

import calc.cliente.util.Util;
import calc.cliente.controller.ClienteController;
import java.awt.EventQueue;

/**
 *
 * @author guilh
 */
public class ClientMain extends javax.swing.JFrame {

    
    private String teste;
    private ClienteController controller;

    /**
     * Creates new form ClientMain
     */
    public ClientMain() {
        
        controller = new ClienteController();
        
        
        initComponents();
        
        
        teste = controller.configuraConexao();
        
    }
                        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        console = new javax.swing.JTextArea();
        btn_result = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        console.setColumns(20);
        console.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        console.setRows(5);
        jScrollPane1.setViewportView(console);

        btn_result.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_result.setText("Stress Test");
        btn_result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                    .addComponent(btn_result, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_result, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btn_resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resultActionPerformed
        // TODO add your handling code here:
        
        String calculo = ("2 + 2");
        
        
        double startTime = System.currentTimeMillis();
        int h = 1;
        double totalTime = 0;
        while(totalTime < 60){
            h = h * 5;
        if (calculo != "0") {
            if (Util.verificaOperador(calculo)) {
                if (calculo.endsWith(",")) {
                    calculo = calculo.substring(0, calculo.length() - 1);
                }
                if (calculo.endsWith(Util.getOperador(calculo))) {
                    calculo += calculo.substring(0, calculo.length() - 1);
                }
                
                for(int i = 0; i < h; i++){
                    String resposta = controller.calcular(calculo);
                    
                }
                console.append("\n"+ "Numero de Operações: " +Integer.toString(h) + " > " +" tempo =" + (System.currentTimeMillis() - startTime) / 1000 +"s");
            }
        }
        
        totalTime = (System.currentTimeMillis() - startTime) / 1000;
        System.out.println(totalTime);
        }
        
        
    }//GEN-LAST:event_btn_resultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        EventQueue.invokeLater(new Runnable() {
            public void run() {
		try {
                    ClientMain window = new ClientMain();
                    window.setVisible(true);
                    window.setResizable(false);
                } catch (Exception e) {
                    e.printStackTrace();
				}
		}
	});
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_result;
    private javax.swing.JTextArea console;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}

